[project]
name = "epaper-image-tool"
version = "0.1.0"
description = "電子ペーパー用に画像を加工するサイト"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "jinja2>=3.1.4",
    "numpy>=2.2.4",
    "pillow>=11.2.1",
    "ruff>=0.8.4",
    "uvicorn>=0.34.0",
]
